apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    {{- include "modular-service.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.workloadType "StatefulSet" }}
  clusterIP: None
  {{- else if .Values.service.nodePort.enabled }}
  type: NodePort
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - name: {{ .Values.serviceName }}-port
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      {{- if .Values.service.nodePort.enabled }}
      nodePort: {{ .Values.service.nodePort.port }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "modular-service.selectorLabels" . | nindent 4 }}
