apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  labels:
    {{- include "main-config.labels" . | nindent 4 }}
data:
  main.config: |-
    api_token: will-be-injected
    session_secret: will-be-injected
    monitoring_api_key: will-be-injected
    monitoring_secret: will-be-injected
    monitoring_api_token_lifetime_min: {{ .Values.config.monitoringApiTokenLifetimeMin }}

    logger:
      level: {{ .Values.config.logging.level }}
      buffered_debug: {{ .Values.config.logging.bufferedDebug }}
      buffer_size: {{ .Values.config.logging.bufferSize }}
      monitoring: {{ .Values.config.logging.monitoring }}
      metrics_interval_s: {{ .Values.config.logging.metricsIntervalS }}
      log_rotate:
        max_mb: {{ .Values.config.logging.logRotateMaxMb }}
        max_backup_files: {{ .Values.config.logging.logRotateMaxBackup }}
        check_interval_s: {{ .Values.config.logging.logRotateCheckIntervalS }}

    data_warehouse:
      type: elastic
      hosts:
        - {{ .Values.config.elasticsearch.hosts }}
      schema: {{ .Values.config.elasticsearch.schema }}
      user: elastic
      password: will-be-injected
      port: {{ .Values.config.elasticsearch.port }}
      ssl_validation: {{ .Values.config.elasticsearch.sslValidation }}
      ca_file:
      request_timeout: {{ .Values.config.elasticsearch.requestTimeout }}
      read_timeout: {{ .Values.config.elasticsearch.readTimeout }}

    postgres:
      user: {{ .Values.config.postgres.user }}
      password: will-be-injected
      host: {{ .Values.config.postgres.host }}
      pg_port: {{ .Values.config.postgres.port }}
      database: {{ .Values.config.postgres.database }}

    kafka:
      producer_batch_size: {{ .Values.config.kafka.producerBatchSize }}
      broker_list:
        - {{ .Values.config.kafka.brokerList }}

    resource_manager:
      url: {{ .Values.config.hypervisor.url | quote }}

    arcanna_infra:
      url: {{ .Values.config.arcannaInfra.url | quote }}

    seal:
      token: will-be-injected

    redis:
      host: {{ .Values.config.redis.host }}
      port: {{ .Values.config.redis.port }}
      password: will-be-injected

    code_block:
      memory_limit: {{ .Values.config.codeBlock.memoryLimit }}
      timeout_limit: {{ .Values.config.codeBlock.timeoutLimit }}
      n_of_workers: {{ .Values.config.codeBlock.nOfWorkers }}

    core:
      security:
        token: will-be-injected

    agents_exposer:
      url: {{ .Values.config.agentsExposer.url | quote }}

    arcanna_rag:
      url: {{ .Values.config.arcannaRag.url | quote }}
      api_key: will-be-injected