apiVersion: v1
kind: Service
metadata:
  name: tei-embeddings
  labels:
    {{- include "tei-embeddings.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    {{- include "tei-embeddings.selectorLabels" . | nindent 4 }}
