apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "arcanna-kibana.labels" . | nindent 4 }}
spec:
  version: {{ .Values.version }}
  count: {{ .Values.count }}
  elasticsearchRef:
    name: {{ .Values.elasticsearchRef }}
  {{- if .Values.publicBaseUrl }}
  config:
    server.publicBaseUrl: {{ .Values.publicBaseUrl | quote }}
  {{- end }}
  {{- if or .Values.tls.selfSignedCertificate.disabled .Values.neg.enabled }}
  http:
    {{- if .Values.tls.selfSignedCertificate.disabled }}
    tls:
      selfSignedCertificate:
        disabled: true
    {{- end }}
    {{- if .Values.neg.enabled }}
    service:
      metadata:
        annotations:
          cloud.google.com/neg: '{"exposed_ports": {"5601": {"name": "{{ .Values.neg.name }}"}}}'
    {{- end }}
  {{- end }}
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
