apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStoreName }}
  target:
    name: redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.redisSecretName }}
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None