apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStoreName }}
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: {{ .Values.postgresSecretName }}
        property: user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: {{ .Values.postgresSecretName }}
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: database
      remoteRef:
        key: {{ .Values.postgresSecretName }}
        property: database
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None