apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arcanna-app-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStoreName }}
  target:
    name: arcanna-app-credentials
    creationPolicy: Owner
  data:
    - secretKey: seal-token
      remoteRef:
        key: {{ .Values.appCredentialsSecretName }}
        property: sealToken
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: api-token
      remoteRef:
        key: {{ .Values.appCredentialsSecretName }}
        property: apiToken
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: rag-api-key
      remoteRef:
        key: {{ .Values.appCredentialsSecretName }}
        property: ragApiKey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: monitoring-api-key
      remoteRef:
        key: {{ .Values.appCredentialsSecretName }}
        property: monitoringApiKey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: monitoring-secret
      remoteRef:
        key: {{ .Values.appCredentialsSecretName }}
        property: monitoringSecret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None