apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-log-pvc
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.logVolume.size }}
  {{- if .Values.logVolume.storageClassName }}
  storageClassName: {{ .Values.logVolume.storageClassName }}
  {{- end }}
