apiVersion: v1
kind: Service
metadata:
  name: monitoring
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: api-port
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
    - name: index-logs-port
      port: {{ .Values.shipper.port }}
      targetPort: {{ .Values.shipper.port }}
  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
