{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "aiops-rest-api.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  seal-token: {{ .Values.secrets.sealToken | b64enc | quote }}
  api-token: {{ .Values.secrets.apiToken | b64enc | quote }}
  rag-api-key: {{ .Values.secrets.ragApiKey | b64enc | quote }}
  monitoring-api-key: {{ .Values.secrets.monitoringApiKey | b64enc | quote }}
  monitoring-secret: {{ .Values.secrets.monitoringSecret | b64enc | quote }}
{{- end }}
