apiVersion: v1
kind: Service
metadata:
  name: aiops-rest-api-http
  labels:
    {{- include "aiops-rest-api.labels" . | nindent 4 }}
  {{- if .Values.service.backendConfig.enabled }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "aiops-rest-api.fullname" . }}-backend-config"}'
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.core.port }}
      protocol: TCP
  selector:
    {{- include "aiops-rest-api.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: aiops-rest-api
  labels:
    {{- include "aiops-rest-api.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.core.port }}
      nodePort: {{ .Values.service.nodePort.port }}
      protocol: TCP
  selector:
    {{- include "aiops-rest-api.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.backendConfig.enabled }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "aiops-rest-api.fullname" . }}-backend-config
  labels:
    {{- include "aiops-rest-api.labels" . | nindent 4 }}
spec:
  timeoutSec: {{ .Values.service.backendConfig.timeoutSec }}
  healthCheck:
    checkIntervalSec: {{ .Values.service.backendConfig.healthCheckIntervalSec }}
    timeoutSec: {{ .Values.service.backendConfig.healthCheckTimeoutSec }}
    port: {{ .Values.config.core.port }}
    type: HTTP
    requestPath: /
{{- end }}
