apiVersion: v1
kind: Service
metadata:
  name: arcanna-rag
  labels:
    {{- include "arcanna-rag.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    {{- include "arcanna-rag.selectorLabels" . | nindent 4 }}
